### ISSUE TITLE
'url' is not a valid tag or filter in tag library 'future'

### ISSUE THREAD

**Issue by anadahalli** [brutasse/django-rq-dashboard#9]
I'm getting this error.
```python
'url' is not a valid tag or filter in tag library 'future'
```
In Django 1.9, url template tag was removed from the future template tag library.

**Comment by ActionScripted** [comment]
Here's how they fixed in the Django Debug Toolbar:
https://github.com/tim-schilling/django-debug-toolbar/commit/833b297999abd994e57702ab7e313149f9ef5fa4

Really, it could just be removed since this is for Django <= 1.5. Remove the call, bump requirements in readme from 1.4 to 1.6+ or implement what DDT did.

Happy to submit a pull request.

**Comment by brutasse** [comment]
@ActionScripted sure, go ahead! Thank you :)
